require "fg-quickgenerate/version"

module Fg
  module Quickgenerate
    # Your code goes here...
    # Ohhh, I don't want to refactor :P
  end
end

module FactoryGirl
  module Syntax::Methods
    def sequential(string)
      name = :"___autogenerated_#{string}___"

      begin
        sequence = FactoryGirl.sequence_by_name(name)
      rescue Exception => e
        sequence = FactoryGirl.create_simple_sequence(name, string)
      end

      sequence.next
    end
  end

  def self.create_simple_sequence(name, string)
    sequence = Sequence.simple(name, string)
    FactoryGirl.register_sequence(sequence)
  end

  class Sequence
    SIMPLE_REPLACEMENT = "#N"

    def self.simple(name, string)
      string += SIMPLE_REPLACEMENT unless string.include? SIMPLE_REPLACEMENT
      Sequence.new(name){|n| string.gsub(SIMPLE_REPLACEMENT, n.to_s)}
    end
  end
end

